name: callee
on:
  push:
    paths:
      - ".github/workflows/caller.yml"
  workflow_dispatch:

jobs:
  call_workflow:
    uses: ./.github/workflows/test.yml
    with:
      rebuild: extra
  download_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: file
      - run: |
          ls -R
          cat file

  