name: mirror
on:
  push:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  dump:
    name: dump mediawiki xml
    runs-on: ubuntu-20.04
    steps:
      - name: prepare
        shell: bash
        run: |
          sudo apt update
          sudo apt install python2-dev python2 -y
          wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
          sudo python2 get-pip.py
          pip2 install kitchen Requests mwclient lxml

  # mirror:
  #   runs-on: ubuntu-latest
  #   container: openzim/zimit
  #   steps:
  #     - name: zimit
  #       shell: bash
  #       run: |
  #           zimit \
  #           --url https://rosettacode.org \
  #           --name rosettacode \
  #           --workers 4 \
  #           --waitUntil domcontentloaded \
  #           --exclude 'User_talk:|Talk:|User:|wiki/Special:' \
  #           --timeLimit 19200
  #
  #     - name: Upload ZIM file
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: rosettacode.zim
  #         path: /output/rosettacode*.zim
