name: mirror
on:
  push:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    container: openzim/zimit
    steps:
      - name: zimit
        shell: bash
        run: |
            zimit \
            --url https://rosettacode.org \
            --name rosettacode \
            --workers 4 \
            --waitUntil domcontentloaded \
            --exclude 'User_talk:|Talk:|User:|action=history|oldid=|RecentChangesLinked|WhatLinksHere|Special:Browse|Special:CentralAuth|Special:Contributions|Special:ManageWiki|Special:Version|Special%3ABrowse|Special%3ACentralAuth' \
            --timeLimit 19200
      - name: Upload ZIM file
        uses: actions/upload-artifact@v3
        with:
          name: rosettacode.zim
          path: /output/rosettacode*.zim
