name: mirror
on:
  push:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          sudo apt update
          apt upgrade -y

      - name: install dependencies
        run: |
          sudo apt install build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ninja-build qemu-system-gui qemu-system-x86 qemu-utils ccache rsync unzip texinfo libssl-dev gcc-12 g++-12

      - name: build
        run: |
          git clone --depth 1 https://github.com/SerenityOS/serenity
          cd serenity
          ./Meta/serenity.sh image

      - name: create artifact
        working-directory: ./serenity
        run: |
          tar -zcvf build.tar.gz ./Build


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./serenity/

  # mirror:
    # runs-on: ubuntu-latest
    # container: openzim/zimit
    # steps:
    #   - name: zimit
    #     shell: bash
    #     run: |
    #         zimit \
    #         --url https://rosettacode.org \
    #         --name rosettacode \
    #         --workers 4 \
    #         --waitUntil domcontentloaded \
    #         --exclude 'User_talk:|Talk:|User:|action=history|oldid=|RecentChangesLinked|WhatLinksHere|Special:Browse|Special:CentralAuth|Special:Contributions|Special:ManageWiki|Special:Version|Special%3ABrowse|Special%3ACentralAuth' \
    #         --timeLimit 19200
    #   - name: Upload ZIM file
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: rosettacode.zim
    #       path: /output/rosettacode*.zim

