name: mirror
on:
  push:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  mirror:
    timeout-minutes: 720
    runs-on: ubuntu-latest
    steps:
      - name: zimit
        shell: bash
        run: |
          docker run -v /output:/output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb \
            openzim/zimit zimit \
            --url https://rosettacode.org \
            --name rosettacode \
            --workers 8 \
            --waitUntil domcontentloaded \
            --exclude 'User_talk:|Talk:|User:' \
            --timeLimit 19000

      - name: Upload ZIM file
        uses: actions/upload-artifact@v3
        with:
          name: rosettacode.zim
          path: /output/rosettacode*.zim
