name: mirror
on:
  push:
  workflow_dispatch:


jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          lscpu
          free -m
          df -h

