name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    container: 
        image: archlinux:base-devel
    steps:
      - name: prepare
        run: |
          pacman -Sy archlinux-keyring --needed --noconfirm
          pacman -Syu --noconfirm
          pacman -S dust --noconfirm
      - name: disk capacity
        run: df -h
      - name: pwd
        run: pwd
      - name: dust
        run: dust /