name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    # container: 
    #     image: archlinux:base-devel
    steps:
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
