name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: input
        id: step_input
        run: |
          echo var=hello > ${GITHUB_OUTPUT}
      - name: output
        id: step_output
        run:
          echo ${{steps.step_input.outputs.var}}