name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:
  workflow_call:
    inputs:
      rebuild:
        required: true
        type: string
        default: full
        description: |
          - full: update pkgver and rebuild kernel and extra modules 
          - extra: rebuild only extra modules for the latest released kernel
# The build workflow has three build types
# - tagged build,  
permissions:
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "input=\"${{inputs.rebuild}}\""
          echo output > file
          echo bump test 4
      - uses: actions/upload-artifact@v3
        with:
          name: file
          path: file