name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: init
        shell: bash
        run: |
          echo "hello world" > cache_file
      # - name: restore cache
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: cache_file
      #     key: cache1

      - name: create cache
        uses: actions/cache/save@v3
        with:
          path: cache_file
          key: cache1
      # - name: delete cache
        
      