name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:
  
permissions:
  contents: write
  actions: write

jobs:
  check_:
    runs-on: ubuntu-latest
    
    steps:
      - name: set variable
        run: |
          echo TEST1=content2 >> "${GITHUB_ENV}"
      - name: test variables
        shell: bash
        run: |
          echo ${{ vars.TEST1 }}