name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:
    inputs:
      var1:
        type: boolean
        description: test variable 1
        required: false
        default: false

jobs:
  clean_up_test:
    runs-on: ubuntu-22.04
    steps:
      - name: test
        run: |
          if [[ -n "${{inputs.var1}}" ]]; then
            echo input var is not empty
            echo ${{ inputs.var1 }}
          else
            echo input var is empty
          fi
