name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:
    inputs:
      var1:
        type: string
        description: test variable 1
        required: false

jobs:
  clean_up_test:
    runs-on: ubuntu-22.04
    steps:
      - name: test
        run: |
          echo {{ input.var1 }}
          