name: test
on:
  push:
    paths:
      - ".github/**"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  actions: write
  
defaults:
  run:
    shell: bash
env:
  artifact_name: linux-clang
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello > file
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: 'file'
          tag_name: 6.4.7.arch1-1.1690905259