name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: test large artifact
        id: test
        run: |
          dd if=/dev/urandom bs=1M count=1124 of=flie status=progress
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with: 
          retention-days: 1
          name: test_large_file
          path: |
            file
