name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:
  
permissions:
  contents: write
  actions: write

jobs:
  check_:
    runs-on: ubuntu-latest
    
    steps:
      - shell: bash
        run: |
          echo ${{ vars.TEST1 }}