name: test
on:
  push:
    paths:
      - ".github/**"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  actions: write
  
defaults:
  run:
    shell: bash
env:
  artifact_name: linux-clang
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: github env test
        run: |
          echo 'test_var_1="test via GITHUB_ENV"' >> "${GITHUB_ENV}"
          echo 'test_var_2="test via github.env"' >> "${{github.env}}"
      - name: get env
        run: |
          echo ${{env.test_var_1}}
          echo ${{env.test_var_2}}
          echo ${{env.step_env}}
          echo ${{env.artifact_name}}
        env:
          step_env: test via steps[].env
      - name: download non-existent artifact
        uses: actions/download-artifact@v3
        with:
          name: non_existent
