name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:
  workflow_call:
    inputs:
      rebuild:
        required: true
        type: string
        default: full
        description: |
          - full: rebuild kernel and extra modules

          - extra: rebuild only extra modules for the latest released kernel
          
permissions:
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print input
        run: |
          echo "input=\"${{inputs.rebuild}}\""