name: test
on:
  push:
    paths:
      - ".github/*"
  workflow_dispatch:
  workflow_call:
    inputs:
      rebuild:
        required: true
        type: string
        default: full
        description: |
          - full: update pkgver and rebuild kernel and extra modules 
          - extra: rebuild only extra modules for the latest released kernel
# The build workflow has three build types
# - tagged build,  
permissions:
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: github env test
        run: |
          echo 'test_var_1="test via GITHUB_ENV"' >> "${GITHUB_ENV}"
          echo 'test_var_2="test via github.env"' >> "${{github.env}}"
      - name: get env
        run: |
          echo ${{env.test_var_1}}
          echo ${{env.test_var_2}}
          