name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  clean_up_test:
    runs-on: ubuntu-22.04
    container: 
      image: archlinux:base-devel 
    steps:
      - name: prepare
        run: |
          pacman -Syu --noconfirm fd
          useradd -m runner
          echo "runner ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
    #   - name: cleanup
    #     run: |
    #       sudo mkdir /empty -p
    #       _files=(
    #         /usr/local/lib/android
    #         /usr/local/.ghcup
    #         /usr/local/share/powershell
    #         /usr/local/share/chromium
    #         /usr/local/share/vcpkg
    #         /usr/share/dotnet
    #         /usr/share/swift
    #         /opt/hostedtoolcache/CodeQL
    #       )
    #       echo ${_files[@]} | sudo xargs -n1 rsync -a --delete /empty/
      - name: Debugging with ssh
        uses: memchr/action-upterm@v0.2
      - name:
        run: |
          echo HOME is $HOME
          ls /
          ls -al $HOME
          fd sock$ $HOME /tmp 

