name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  clean_up_test:
    runs-on: ubuntu-22.04
    container: 
      image: archlinux:base-devel 
      options: --privileged
      volumes:
        - /:/host
    steps:
      - name: prepare
        run: |
          pacman -Syu --noconfirm --needed gdu  rsync
      - name: ssh debug
        uses: mxschmitt/action-tmate@v3
        with:
           detached: true
      - name: Freeup space
        run: |
          sudo mkdir /empty -p
          _files=(
            /usr/local/lib/android
            /usr/local/.ghcup
            # /usr/local/share/powershell
            # /usr/local/share/chromium
            # /usr/local/share/vcpkg
            # /usr/share/dotnet
            # /usr/share/swift
            # /opt/hostedtoolcache/CodeQL
          )
          for f in ${_files[@]}; do 
            rsync -a --delete /empty/ "/host/$f"
          done

