name: test
on:
  push:
    paths:
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: test
        run: |
          echo "var=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-22.04
    needs: job1
    steps:
      - name: test output
        run: |
          echo var is ${{needs.job1.outputs.var}}